 'use client';
import { useState,useEffect } from 'react';
import { useSearchParams } from 'next/navigation';
import { ZoomIn,ArrowUpRight } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { gallery } from '@/lib/gallery';
const categories=['All','Nicole Milano','Luna Novias','Adriana Alier','White One','The boutique'];
export function Gallery(){const query=useSearchParams();const initial=query.get('designer')||'All';const [category,setCategory]=useState(categories.includes(initial)?initial:'All');const [selected,setSelected]=useState<(typeof gallery)[number]|null>(null);
 useEffect(()=>{const mc=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(mc.registerTool({name:'filter_bridal_gallery',title:'Filter bridal photographs',description:'Show the selected designer in the visible bridal gallery. This does not reserve a dress or book an appointment.',inputSchema:{type:'object',properties:{designer:{type:'string',enum:categories}},required:['designer'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const value=(input as {designer?:unknown})?.designer;if(typeof value!=='string'||!categories.includes(value))throw new Error('Choose a listed designer or All.');setCategory(value);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{designer:value,dresses:gallery.filter(g=>value==='All'||g.designer===value).map(g=>({name:g.name,designer:g.designer}))}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 return <><Tabs value={category} onValueChange={setCategory} className="gallery-tabs"><TabsList aria-label="Filter photographs by designer">{categories.map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList>{categories.map(c=>{const items=gallery.filter(g=>c==='All'||g.designer===c);return <TabsContent value={c} key={c}><p className="gallery-count">{String(items.length).padStart(2,'0')} PHOTOGRAPHS · {c==='All'?'THE COMPLETE EDIT':c.toUpperCase()}</p><div className="gallery-grid">{items.map((g,i)=><button className="gallery-item" key={g.src} onClick={()=>setSelected(g)} aria-label={'View '+g.name+' by '+g.designer}><div className="gallery-photo"><img src={g.src} alt={g.alt} width={g.width} height={g.height} loading={i<3?'eager':'lazy'}/><span className="zoom-icon"><ZoomIn size={18}/></span></div><h3>{g.name}</h3><p>{g.designer}</p></button>)}</div></TabsContent>})}</Tabs><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="gallery-dialog">{selected&&<><img src={selected.src} alt={selected.alt} width={selected.width} height={selected.height}/><div className="dialog-bottom"><div><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.designer}</DialogDescription></div><a className="text-link" href={selected.designer==='The boutique'?'/appointments':'/appointments?designer='+encodeURIComponent(selected.designer)+'&dress='+encodeURIComponent(selected.name)}>{selected.designer==='The boutique'?'Arrange your visit':'Ask about this dress'} <ArrowUpRight size={16}/></a></div></>}</DialogContent></Dialog></>}

