import type { Metadata } from 'next';
import { Suspense } from 'react';
import { MapPin,Phone,Mail,Clock,ArrowUpRight } from 'lucide-react';
import { PageIntro } from '@/components/bridal/shared';
import { AppointmentForm } from '@/components/bridal/appointment-form';
import { site } from '@/lib/bridal';
export const metadata:Metadata={title:'Arrange Your Bridal Appointment',description:'Request a private appointment at Courtyard Bridal, 19 West Street, Tollesbury, Essex. Call 07894 009403 or send your preferred date by email.',alternates:{canonical:'/appointments'}};
export default function Appointments(){return <main id="main-content"><PageIntro eyebrow="Let’s talk dresses" title="Your next chapter" italic="starts here." text="Tell us a little about your plans and a day that suits you. We’ll confirm availability and help you arrange your visit."/><section className="section contact-layout"><aside className="contact-aside"><img src="/images/luna-novias-soyer.webp" alt="Soyer by Luna Novias, a gown from the Courtyard Bridal collection" width="800" height="943"/><div className="contact-detail"><MapPin/><div><h2>Find our new home</h2><p>19 West Street<br/>Tollesbury, Essex<br/>CM9 8RJ</p><a className="text-link" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=19%20West%20Street%2C%20Tollesbury%2C%20CM9%208RJ">Open directions <ArrowUpRight size={15}/></a></div></div><div className="contact-detail"><Phone/><div><h2>Give us a call</h2><a href={'tel:'+site.phone}>{site.displayPhone}</a></div></div><div className="contact-detail"><Mail/><div><h2>Write to us</h2><a href={'mailto:'+site.email}>{site.email}</a></div></div><div className="contact-detail"><Clock/><div><h2>By appointment</h2><p>Please arrange your visit before travelling. Ask us about a day and time that works for you.</p><a className="text-link" href={site.facebook} target="_blank" rel="noreferrer">Arrange through Facebook <ArrowUpRight size={15}/></a></div></div></aside><Suspense fallback={<div className="appointment-form"><h2>Your appointment</h2><p>Opening your enquiry…</p></div>}><AppointmentForm/></Suspense><section id="privacy" className="privacy-note"><h2>Privacy & enquiries</h2><p>The enquiry form prepares a message in your email app. Your details are only sent when you choose to send that email to {site.email}. The form does not store your details on this website.</p><p>Please only include information relevant to your appointment. Contact the boutique directly if you have questions about how your email enquiry is handled. Following a Facebook or Google Maps link takes you to that service, where its own privacy terms apply.</p></section></section></main>}

