import { ArrowDown, ArrowUpRight, Heart, DoorOpen, Scissors } from 'lucide-react';
import { AppointmentBanner, CollectionCards, Eyebrow } from '@/components/bridal/shared';
export default function Home() {
 return <main id="main-content">
  <section className="hero"><div className="hero-copy"><Eyebrow>A little boutique. A very special dress.</Eyebrow><h1>A dress that<br/>feels like <em>you.</em></h1><p>For the butterflies, the happy tears, and the moment it all feels right. Find your wedding dress with us in Tollesbury, Essex.</p><a className="button" href="/appointments">Your appointment awaits <ArrowUpRight size={18}/></a><a className="hero-discover" href="#collections"><ArrowDown size={17}/> Discover your dress</a></div><div className="hero-image"><img src="/images/hero.webp" alt="Designer bridal gown from the Courtyard Bridal collection" width="1000" height="1250" fetchPriority="high"/><div className="image-label"><span>THE COURTYARD EDIT</span><span>Modern romance, made personal.</span></div></div><span className="hero-side-note">TOLLESBURY, ESSEX · BY APPOINTMENT</span></section>
  <div className="designer-strip" aria-label="Our bridal designers"><span>Beautifully chosen</span><b>Nicole Milano</b><b>Luna Novias</b><b>ADRIANA ALIER</b><b>WHITE ONE</b></div>
  <section className="section collections-section" id="collections"><div className="section-heading"><div><Eyebrow>The collections</Eyebrow><h2>Meet your <em>maybe.</em></h2></div><div><p>A first look. A favourite detail. A shape you hadn’t considered.<br className="desktop-only"/> There’s more than one way to fall for a dress.</p><a href="/collections" className="text-link">Explore the collections <ArrowUpRight size={17}/></a></div></div><CollectionCards/></section>
  <section className="experience-split"><div className="experience-photo"><img src="/images/experience.webp" alt="A personal touch at Courtyard Bridal" width="850" height="1100" loading="lazy"/></div><div className="experience-copy"><Eyebrow>The Courtyard experience</Eyebrow><h2>Your dress.<br/>Your people.<br/><em>Your moment.</em></h2><p>A private appointment, a friendly face and space to find your own style. Your consultant stays with you from your first visit through to collecting your dress.</p><div className="small-benefits"><span><DoorOpen/> A private setting</span><span><Heart/> One-to-one attention</span><span><Scissors/> A personal style consultation</span></div><a href="/experience" className="text-link">A little more about your visit <ArrowUpRight size={17}/></a></div></section>
  <section className="section gallery-teaser"><div className="section-heading"><div><Eyebrow>A closer look</Eyebrow><h2>It’s all in <em>the details.</em></h2></div><a href="/gallery" className="text-link">Step into the gallery <ArrowUpRight size={17}/></a></div><div className="teaser-grid">{['detail-one','detail-two','detail-three'].map((name,i)=><a href="/gallery" key={name}><img src={'/images/'+name+'.webp'} alt={['Romantic lace and delicate bridal detailing','A beautifully structured designer wedding dress','A gown from the Courtyard Bridal designer edit'][i]} width="700" height="950" loading="lazy"/><span>Explore the details <ArrowUpRight size={17}/></span></a>)}</div></section>
  <section className="review-invitation"><Eyebrow>From one bride to another</Eyebrow><h2>The experience matters<br/>as much as <em>the dress.</em></h2><p>Read the recommendations on our Facebook page and get a feel for Courtyard before your visit.</p><a href="/kind-words" className="text-link">Read our brides’ recommendations <ArrowUpRight size={17}/></a></section><AppointmentBanner/>
 </main>;
}
